spring:
  application:
    name: expense

  datasource:
    url: jdbc:mysql://localhost:3306/expense-reimbursement?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root4321

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 5MB   # الحد الأقصى لحجم الملف

app:
  jwt:
    secret: Y2hhbmdlZC10aGlzLXRvLWEtc3Ryb25nLXJhbmRvbS1iYXNlNjQtc3RyaW5n
    expiration-minutes: 60



file:
  upload-dir: uploads/  # المجلد اللي تتخزن فيه الملفات
