app:
  jwt:
    secret: "change-this-to-a-strong-random-base64-string"
    expiration-minutes: 60
spring:
  datasource:
    url: jdbc:h2:mem:expensedb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# your existing JWT config stays here
app:
  jwt:
    secret: "CHANGE_ME_BASE64"
    expiration-minutes: 60
